### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by bert** [makerbot/ToolPathViz#4]
Hi,

I just did a fresh git clone,started qt4-creator and loaded GCodeViewer.pro and started "build all".

Got the following error report:

Running build steps for project GCodeViewer...
Starting: /usr/bin/qmake-qt4 /home/bert/workspace/external/ToolPathViz/GCodeViewer.pro -spec linux-g++ -r CONFIG+=debug
Exited with code 0.
Starting: /usr/bin/make -w
make: Entering directory `/home/bert/workspace/external/ToolPathViz'
/usr/lib/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h
g++ -c -pipe -g -Wall -W -D_REENTRANT -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include -I/usr/X11R6/include -I. -I. -o main.o main.cpp
g++ -c -pipe -g -Wall -W -D_REENTRANT -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include -I/usr/X11R6/include -I. -I. -o mainwindow.o mainwindow.cpp
In file included from gcodeview.h:7,
from ui_mainwindow.h:33,
from mainwindow.cpp:10:
gcode.h:11:24: error: mgl/pather.h: No such file or directory
gcode.h:12:25: error: mgl/miracle.h: No such file or directory
gcode.h:13:31: error: mgl/configuration.h: No such file or directory
In file included from ui_mainwindow.h:33,
from mainwindow.cpp:10:
gcodeview.h:10:26: error: mgl/regioner.h: No such file or directory
In file included from gcodeview.h:7,
from ui_mainwindow.h:33,
from mainwindow.cpp:10:
gcode.h:158: error: ‘mgl’ has not been declared
gcode.h:158: error: ISO C++ forbids declaration of ‘GCoderConfig’ with no type
gcode.h:158: error: expected ‘;’ before ‘gcoderCfg’
gcode.h:159: error: ‘mgl’ was not declared in this scope
gcode.h:159: error: template argument 1 is invalid
gcode.h:159: error: template argument 2 is invalid
gcode.h:160: error: ‘mgl’ has not been declared
gcode.h:160: error: ISO C++ forbids declaration of ‘LayerPaths’ with no type
gcode.h:160: error: expected ‘;’ before ‘slicePaths’
gcode.h:161: error: ‘mgl’ has not been declared
gcode.h:161: error: ISO C++ forbids declaration of ‘LayerMeasure’ with no type
gcode.h:161: error: expected ‘;’ before ‘layerMeasure’
gcode.h:183: error: ISO C++ forbids declaration of ‘mgl’ with no type
gcode.h:183: error: expected ‘,’ or ‘...’ before ‘::’ token
gcode.h:187: error: ISO C++ forbids declaration of ‘mgl’ with no type
gcode.h:187: error: expected ‘,’ or ‘...’ before ‘::’ token
gcode.h:187: error: ‘void gcodeModel::loadSliceData(int)’ cannot be overloaded
gcode.h:183: error: with ‘void gcodeModel::loadSliceData(int)’
gcode.h:192: error: ISO C++ forbids declaration of ‘mgl’ with no type
gcode.h:192: error: expected ‘,’ or ‘...’ before ‘::’ token
gcode.h:195: error: ISO C++ forbids declaration of ‘mgl’ with no type
gcode.h:195: error: expected ‘,’ or ‘...’ before ‘::’ token
gcode.h:195: error: ‘void gcodeModel::loadRegions(int)’ cannot be overloaded
gcode.h:192: error: with ‘void gcodeModel::loadRegions(int)’
In file included from ui_mainwindow.h:33,
from mainwindow.cpp:10:
gcodeview.h:22: error: ISO C++ forbids declaration of ‘mgl’ with no type
gcodeview.h:22: error: expected ‘,’ or ‘...’ before ‘::’ token
gcodeview.h:25: error: ISO C++ forbids declaration of ‘mgl’ with no type
gcodeview.h:25: error: expected ‘,’ or ‘...’ before ‘::’ token
gcodeview.h:25: error: ‘void GcodeView::loadSliceData(int)’ cannot be overloaded
gcodeview.h:22: error: with ‘void GcodeView::loadSliceData(int)’
mainwindow.cpp:18: error: ‘mgl’ is not a namespace-name
mainwindow.cpp:18: error: expected namespace-name before ‘;’ token
mainwindow.cpp:23: error: expected class-name before ‘{’ token
mainwindow.cpp: In constructor ‘MainWindow::MainWindow(QWidget*)’:
mainwindow.cpp:84: error: ‘mgl’ has not been declared
mainwindow.cpp: In member function ‘void MainWindow::sliceModelAndCreateToolPaths(const char*)’:
mainwindow.cpp:274: error: ‘MyComputer’ was not declared in this scope
mainwindow.cpp:274: error: expected ‘;’ before ‘computer’
mainwindow.cpp:279: error: ‘computer’ was not declared in this scope
mainwindow.cpp:285: error: ‘mgl’ has not been declared
mainwindow.cpp:285: error: expected ‘;’ before ‘config’
mainwindow.cpp:287: error: ‘config’ was not declared in this scope
mainwindow.cpp:289: error: ‘GCoderConfig’ was not declared in this scope
mainwindow.cpp:289: error: expected ‘;’ before ‘gcoderCfg’
mainwindow.cpp:290: error: ‘gcoderCfg’ was not declared in this scope
mainwindow.cpp:290: error: ‘loadGCoderConfigFromFile’ was not declared in this scope
mainwindow.cpp:291: error: ‘SlicerConfig’ was not declared in this scope
mainwindow.cpp:291: error: expected ‘;’ before ‘slicerCfg’
mainwindow.cpp:292: error: ‘slicerCfg’ was not declared in this scope
mainwindow.cpp:292: error: ‘loadSlicerConfigFromFile’ was not declared in this scope
mainwindow.cpp:293: error: ‘RegionerConfig’ was not declared in this scope
mainwindow.cpp:293: error: expected ‘;’ before ‘regionerCfg’
mainwindow.cpp:294: error: ‘regionerCfg’ was not declared in this scope
mainwindow.cpp:294: error: ‘loadRegionerConfigFromFile’ was not declared in this scope
mainwindow.cpp:295: error: ‘PatherConfig’ was not declared in this scope
mainwindow.cpp:295: error: expected ‘;’ before ‘patherCfg’
mainwindow.cpp:296: error: ‘patherCfg’ was not declared in this scope
mainwindow.cpp:296: error: ‘loadPatherConfigFromFile’ was not declared in this scope
mainwindow.cpp:297: error: ‘ExtruderConfig’ was not declared in this scope
mainwindow.cpp:297: error: expected ‘;’ before ‘extruderCfg’
mainwindow.cpp:298: error: ‘extruderCfg’ was not declared in this scope
mainwindow.cpp:298: error: ‘loadExtruderConfigFromFile’ was not declared in this scope
mainwindow.cpp:311: error: ‘Tomograph’ was not declared in this scope
mainwindow.cpp:311: error: expected ‘;’ before ‘tomograph’
mainwindow.cpp:312: error: ‘LayerLoops’ was not declared in this scope
mainwindow.cpp:312: error: expected ‘;’ before ‘layerloops’
mainwindow.cpp:313: error: ‘RegionList’ was not declared in this scope
mainwindow.cpp:313: error: expected ‘;’ before ‘regions’
mainwindow.cpp:314: error: ‘mgl’ was not declared in this scope
mainwindow.cpp:314: error: template argument 1 is invalid
mainwindow.cpp:314: error: template argument 2 is invalid
mainwindow.cpp:314: error: invalid type in declaration before ‘;’ token
mainwindow.cpp:315: error: ‘LayerPaths’ was not declared in this scope
mainwindow.cpp:315: error: expected ‘;’ before ‘layerpaths’
mainwindow.cpp:317: error: ‘Meshy’ was not declared in this scope
mainwindow.cpp:317: error: expected ‘;’ before ‘mesh’
mainwindow.cpp:318: error: ‘mesh’ was not declared in this scope
mainwindow.cpp:321: error: ‘Limits’ was not declared in this scope
mainwindow.cpp:321: error: expected ‘;’ before ‘limits’
mainwindow.cpp:322: error: ‘Grid’ was not declared in this scope
mainwindow.cpp:322: error: expected ‘;’ before ‘grid’
mainwindow.cpp:324: error: ‘Segmenter’ was not declared in this scope
mainwindow.cpp:324: error: expected ‘;’ before ‘segmenter’
mainwindow.cpp:326: error: ‘segmenter’ was not declared in this scope
mainwindow.cpp:328: error: ‘Slicer’ was not declared in this scope
mainwindow.cpp:328: error: expected ‘;’ before ‘slicer’
mainwindow.cpp:329: error: ‘slicer’ was not declared in this scope
mainwindow.cpp:329: error: ‘layerloops’ was not declared in this scope
mainwindow.cpp:332: error: ‘Regioner’ was not declared in this scope
mainwindow.cpp:332: error: expected ‘;’ before ‘regioner’
mainwindow.cpp:333: error: ‘regioner’ was not declared in this scope
mainwindow.cpp:333: error: ‘regions’ was not declared in this scope
mainwindow.cpp:334: error: ‘limits’ was not declared in this scope
mainwindow.cpp:334: error: ‘grid’ was not declared in this scope
mainwindow.cpp:337: error: ‘Pather’ was not declared in this scope
mainwindow.cpp:337: error: expected ‘;’ before ‘pather’
mainwindow.cpp:338: error: ‘pather’ was not declared in this scope
mainwindow.cpp:339: error: ‘layerpaths’ was not declared in this scope
mainwindow.cpp:349: error: ‘class gcodeModel’ has no member named ‘layerMeasure’
mainwindow.cpp:349: error: ‘tomograph’ was not declared in this scope
mainwindow.cpp:351: error: ‘class gcodeModel’ has no member named ‘slicePaths’
mainwindow.cpp:352: error: ‘class gcodeModel’ has no member named ‘gcoderCfg’
mainwindow.cpp:355: error: expected type-specifier before ‘mgl’
mainwindow.cpp:355: error: expected ‘)’ before ‘::’ token
mainwindow.cpp:355: error: expected ‘{’ before ‘::’ token
mainwindow.cpp:355: error: ‘::Exception’ has not been declared
mainwindow.cpp:355: error: ‘mixup’ was not declared in this scope
mainwindow.cpp:355: error: expected ‘;’ before ‘)’ token
mainwindow.cpp:362: error: expected primary-expression before ‘catch’
mainwindow.cpp:362: error: expected ‘;’ before ‘catch’
make: *** [mainwindow.o] Error 1
make: Leaving directory`/home/bert/workspace/external/ToolPathViz'
Exited with code 2.
Error while building project GCodeViewer
When executing build step 'Make'

Kind regards,

Bert Timmerman

**Comment by bert** [comment]
Ok, google is my friend ;-)

I see that mgl lives in git://github.com/makerbot/Miracle-Grue.git

**Comment by FarMcKon** [comment]
Gland you unblocked yourself, since we are not getting to git issues as quickly as we want.

How was building things? Did you get toolpathviz working as expected?
